catalog: insurance_lakehouse

schemas:
  bronze: bronze
  silver: silver
  quarantine: quarantine

tables:
  bronze_customers: bronze_customers
  bronze_policies: bronze_policies
  bronze_claims: bronze_claims
  bronze_payments: bronze_payments
  bronze_agents: bronze_agents
  bronze_fraud_indicators: bronze_fraud_indicators

  silver_customers: silver_customers
  silver_policies: silver_policies
  silver_claims: silver_claims
  silver_payments: silver_payments
  silver_agents: silver_agents
  silver_fraud_indicators: silver_fraud_indicators
